ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
