obj-$(CONFIG_HUAWEI_SENSORS)				+= sensor/
obj-$(CONFIG_HUAWEI_TOUCH_SCREEN)			+= touchscreen/
obj-y			+= power/
obj-y   += antenna_board_match/
obj-$(CONFIG_RFFE_ANTENNA) += antenna_cable/
obj-y			+= log/
obj-$(CONFIG_RFFE_ANTENNA) += antenna_board_gpio_match/
obj-$(CONFIG_CHR_NETLINK_MODULE)   += chr/
