obj-$(CONFIG_HUAWEI_TOUCH_SCREEN)	+= hw_tp_common.o
#obj-$(CONFIG_HUAWEI_KERNEL) += getevent_common_report.o
obj-$(CONFIG_CYTTSP5_CS445A)		+= cyttsp5_cs445a/
obj-$(CONFIG_SYNAPTICS_DSX_S3320)	+= synaptics_dsx_s3320/
obj-$(CONFIG_FOCALTECH_8736)		+= focaltech_8736/
obj-$(CONFIG_ILITEK_2120) += ilitek_2120/
