ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
