ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_csid.o
