obj-$(CONFIG_LCDKIT_DRIVER)	+= lcdkit_panel.o
obj-$(CONFIG_LCDKIT_DRIVER)	+= lcdkit_fb_util.o
obj-$(CONFIG_LCDKIT_DRIVER)	+= lcdkit_debug.o
obj-$(CONFIG_LCDKIT_DRIVER)	+= lcdkit_parse.o
obj-$(CONFIG_LCDKIT_DRIVER)	+= qcom/

EXTRA_CFLAGS += -Idrivers/devkit/lcdkit/include \
		-Idrivers/devkit/tpkit
