ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/common/
obj-$(CONFIG_MSMB_CAMERA) += msm_buf_mgr.o msm_isp_util.o msm_isp_axi_util.o msm_isp_stats_util.o
obj-$(CONFIG_MSMB_CAMERA) += msm_isp48.o msm_isp47.o msm_isp46.o msm_isp44.o msm_isp40.o msm_isp.o
