obj-$(CONFIG_HUAWEI_HALL_SENSORS)			+= hallsensor/
obj-$(CONFIG_HUAWEI_LP_SENSORS)				+= lpsensor/
obj-$(CONFIG_SENSOR_DEVELOP_TEST)			+= develop_test.o
obj-$(CONFIG_HUAWEI_SENSOR_INFO)			+= hw_sensor_info.o
