# Makefile for panel/touchscreen drivers !

obj-$(CONFIG_HUAWEI_TS_KIT) += qcom_adapter/
obj-$(CONFIG_HUAWEI_TS_KIT)  += huawei_ts_kit_core.o
obj-$(CONFIG_HUAWEI_TS_KIT)  += huawei_ts_kit_fsnode.o
obj-$(CONFIG_HUAWEI_TS_KIT)  += huawei_ts_kit_api.o
obj-$(CONFIG_HUAWEI_TS_KIT)  += huawei_ts_kit_algo.o
obj-$(CONFIG_HUAWEI_TS_KIT)  += panel/
obj-$(CONFIG_HUAWEI_TS_KIT)  += huawei_ts_kit_csvparse.o
obj-$(CONFIG_HUAWEI_TP_KIT_COLOR_INFO) += tp_color.o
