#
# for CA8 cpu stress test
#

obj-$(CONFIG_CPU_STRESS_TEST) += slt_fp0_maxpower.o slt_fp0_maxpower_asm.o \
           slt_fp1_memtestL2.o slt_fp1_memtestL2_asm.o \
           slt_fp2_memcpyL1.o slt_fp2_memcpyL1_asm.o \
           slt_fp3_memcpyL2.o slt_fp3_memcpyL2_asm.o \
#           slt_fp4_vfp_func.o slt_fp4_vfp_func_asm.o \
#           slt_fp7_fdct.o slt_fp7_fdct_asm.o \


#KBUILD_AFLAGS	:=$(KBUILD_AFLAGS:-msoft-float=-Wa,-mfpu=neon-vfpv4)
