ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_huawei/sensor/cci
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
