	{
		"hi553_qtech_zh553ab_pad",
		hi553_otp_func,
		HI553S_QTECH_RG_RATIO_TYPICAL,
		HI553S_QTECH_BG_RATIO_TYPICAL,
		true,
	},
        {
                "hi553_chicony_cjag523_pad",
                hi553_otp_func,
                HI553S_CHICONY_RG_RATIO_TYPICAL,
                HI553S_CHICONY_BG_RATIO_TYPICAL,
                true,
        },
